---
- hosts: docker_hosts
  roles:
    - geerlingguy.docker
  pre_tasks:
    - name: Install apt_key prerequisites
      package:
        name: gnupg
        state: present
  post_tasks:
    - name: Use journald log driver for docker
      copy:
        content: '{"log-driver": "journald", "storage-driver":"devicemapper"}'
        dest: /etc/docker/daemon.json
      notify: restart docker
  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted


- hosts: k8s_hosts
  roles:
    - geerlingguy.kubernetes
  post_tasks:
    - name: Stop and disable kubelet until kubeadm init
      service:
        name: kubelet
        state: stopped
        enabled: false
