---
name: 📦 Build Packer Images
on: [push]
jobs:
  packer-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install packer dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends qemu qemu-kvm qemu-efi-aarch64
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install packer
        run: wget --no-verbose http://http.us.debian.org/debian/pool/main/p/packer/packer_1.3.4+dfsg-4+b1_amd64.deb && sudo dpkg -i packer_1.3.4+dfsg-4+b1_amd64.deb

      - name: Build packer image
        run: /usr/bin/packer build debian-arm64.json

      - name: Build packer image with debug info (on build failure)
        if: ${{ failure() }}
        run: /usr/bin/packer build debian-arm64.json
        env:
          PACKER_LOG: 1

      - name: Upload raw qemu image
        id: upload_artifact_retry_0
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: debian-arm64.img
          path: output-qemu/debian-arm64

      - name: Upload raw qemu image - retry 1
        id: upload_artifact_retry_1
        continue-on-error: true
        if: steps.upload_artifact_retry_0.outcome=='failure'
        uses: actions/upload-artifact@v2
        with:
          name: debian-arm64.img
          path: output-qemu/debian-arm64

      - name: Upload raw qemu image - retry 2
        id: upload_artifact_retry_2
        continue-on-error: true
        if: steps.upload_artifact_retry_1.outcome=='failure'
        uses: actions/upload-artifact@v2
        with:
          name: debian-arm64.img
          path: output-qemu/debian-arm64

      - name: Upload raw qemu image - retry 3
        id: upload_artifact_retry_3
        continue-on-error: true
        if: steps.upload_artifact_retry_2.outcome=='failure'
        uses: actions/upload-artifact@v2
        with:
          name: debian-arm64.img
          path: output-qemu/debian-arm64

      - name: Upload raw qemu image - retry 4
        id: upload_artifact_retry_4
        continue-on-error: true
        if: steps.upload_artifact_retry_3.outcome=='failure'
        uses: actions/upload-artifact@v2
        with:
          name: debian-arm64.img
          path: output-qemu/debian-arm64

      - name: Upload raw qemu image - retry 5
        id: upload_artifact_retry_5
        continue-on-error: true
        if: steps.upload_artifact_retry_4.outcome=='failure'
        uses: actions/upload-artifact@v2
        with:
          name: debian-arm64.img
          path: output-qemu/debian-arm64

      - name: Report upload-artifact retry status
        if: always()
        run: |
          if ${{ steps.upload_artifact_retry_0.outcome=='success' || steps.upload_artifact_retry_1.outcome=='success' || steps.upload_artifact_retry_2.outcome=='success' || steps.upload_artifact_retry_3.outcome=='success' || steps.upload_artifact_retry_4.outcome=='success' || steps.upload_artifact_retry_5.outcome=='success' }}; then
             echo success
          else
             exit 1
          fi
