---
name: 📦 Build Packer Images
on: [push]
jobs:
  packer-build:
    timeout-minutes: 120
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install packer dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends qemu qemu-kvm qemu-efi-aarch64
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install packer
        run: wget --no-verbose http://http.us.debian.org/debian/pool/main/p/packer/packer_1.3.4+dfsg-4+b1_amd64.deb && sudo dpkg -i packer_1.3.4+dfsg-4+b1_amd64.deb

      - name: Install debugging packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends tigervnc-viewer
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build packer image
        run: /usr/bin/packer build debian-arm64.json
        env:
          PACKER_LOG: 1
